## Import libraries

In [1]:
import numpy as np
import pandas as pd

### Pandas Version

In [2]:
pd.__version__

'2.2.2'

### Records Count

In [3]:
df = pd.read_csv('laptops.csv')

In [4]:
df.shape[0]

2160

### Laptop Brands

In [5]:
df.Brand.unique().shape[0]

27

### Missing Values

In [6]:
df.isnull().sum().sort_values(ascending = False)

GPU             1371
Storage type      42
Screen             4
Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Touch              0
Final Price        0
dtype: int64

### Maximum Final Price

In [7]:
df[df.Brand=="Dell"]['Final Price'].max()

3936.0

### Median Value of Screen

In [8]:
median = df.Screen.median()

In [9]:
mode = df.Screen.mode()[0]

In [10]:
median, mode

(15.6, 15.6)

In [11]:
df.Screen = df.Screen.fillna(value = mode)

In [12]:
df.Screen.median()

15.6

### Sum of weights

In [13]:
X = df[df.Brand=="Innjoo"][["RAM", "Storage", "Screen"]].to_numpy()

In [14]:
XTX = X.T@X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [15]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [16]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [17]:
w = XTX_inv@X.T@y
w

array([45.58076606,  0.42783519, 45.29127938])

In [18]:
sum(w)

91.2998806299555